# Generated by Django 3.0.5 on 2020-04-17 08:54

from django.db import migrations, models
import django.db.models.deletion
import djangoEcomBackend.eCom.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('catag_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_detail',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=52)),
                ('user_password', models.CharField(max_length=56, null=True)),
                ('email', models.CharField(max_length=52)),
                ('address', models.CharField(max_length=256)),
                ('vinecoins', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product_detail',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=256)),
                ('availability', models.IntegerField()),
                ('price', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('cover', models.ImageField(blank=True, null=True, upload_to=djangoEcomBackend.eCom.models.upload_path)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eCom.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('sup_id', models.AutoField(primary_key=True, serialize=False)),
                ('sup_name', models.CharField(max_length=56)),
                ('sup_password', models.CharField(max_length=56)),
            ],
        ),
        migrations.CreateModel(
            name='Wish_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eCom.Customer_detail')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eCom.Product_detail')),
            ],
        ),
        migrations.AddField(
            model_name='product_detail',
            name='sup_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eCom.Supplier'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pricing', models.IntegerField()),
                ('no_of_product', models.IntegerField()),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eCom.Customer_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Order_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eCom.Customer_detail')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eCom.Product_detail')),
            ],
        ),
    ]
