# Generated by Django 3.0.5 on 2020-08-23 08:45

from django.db import migrations, models
import django.db.models.deletion
import djangoEcomBackend.eCom.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('catag_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_detail',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=52)),
                ('user_password', models.CharField(max_length=56, null=True)),
                ('email', models.CharField(max_length=52)),
                ('address', models.CharField(max_length=256)),
                ('vinecoins', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product_detail',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=256)),
                ('availability', models.IntegerField()),
                ('price', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('cover', models.ImageField(blank=True, null=True, upload_to=djangoEcomBackend.eCom.models.upload_path)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eCom.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('sup_id', models.AutoField(primary_key=True, serialize=False)),
                ('sup_name', models.CharField(max_length=56)),
                ('sup_email', models.CharField(default='no value', max_length=56)),
                ('sup_address', models.CharField(default='no value', max_length=256)),
                ('sup_password', models.CharField(default='no value', max_length=56)),
            ],
        ),
        migrations.CreateModel(
            name='Wish_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eCom.Customer_detail')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eCom.Product_detail')),
            ],
        ),
        migrations.AddField(
            model_name='product_detail',
            name='sup_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eCom.Supplier'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pricing', models.IntegerField()),
                ('no_of_product', models.IntegerField()),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eCom.Customer_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Order_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eCom.Customer_detail')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eCom.Product_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_customer', models.BooleanField(default=False)),
                ('is_supplier', models.BooleanField(default=False)),
                ('cust_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eCom.Customer_detail')),
                ('sup_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eCom.Supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
