# Generated by Django 3.0.5 on 2020-08-23 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eCom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_detail',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer_detail',
            name='user_password',
        ),
        migrations.RemoveField(
            model_name='customer_detail',
            name='username',
        ),
    ]
