# Generated by Django 3.0.5 on 2020-08-23 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eCom', '0002_auto_20200823_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='sup_email',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='sup_name',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='sup_password',
        ),
    ]
