# Generated by Django 3.0.5 on 2020-04-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCom', '0002_auto_20200418_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='sup_address',
            field=models.CharField(default='no value', max_length=256),
        ),
        migrations.AddField(
            model_name='supplier',
            name='sup_email',
            field=models.CharField(default='no value', max_length=56),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sup_password',
            field=models.CharField(default='no value', max_length=56),
        ),
    ]
