# Generated by Django 3.0.5 on 2020-07-27 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eCom', '0003_auto_20200420_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_detail',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eCom.Category'),
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='sup_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eCom.Supplier'),
        ),
    ]
