# Generated by Django 3.0.5 on 2020-09-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCom', '0004_auto_20200823_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_detail',
            name='product_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
