# Generated by Django 3.0.5 on 2020-09-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCom', '0005_product_detail_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_list',
            name='confirmed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order_list',
            name='delivered',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
