# Generated by Django 3.0.5 on 2020-09-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCom', '0006_auto_20200930_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_list',
            name='id',
        ),
        migrations.AddField(
            model_name='order_list',
            name='cancel_order',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order_list',
            name='order_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='order_list',
            name='order_returned',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order_list',
            name='return_order',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
