# Generated by Django 3.0.5 on 2020-09-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCom', '0007_auto_20200930_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_list',
            name='order_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
