# Generated by Django 3.0.5 on 2020-10-04 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eCom', '0008_auto_20200930_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_reviews',
            fields=[
                ('reviews_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('review_title', models.TextField(blank=True, null=True)),
                ('review_des', models.TextField(blank=True, null=True)),
                ('customer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eCom.Product_detail')),
            ],
        ),
    ]
